# Generated by Django 5.0.6 on 2024-05-27 17:54

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('value', models.SlugField(default=core.utils.session_value_genereate, max_length=80, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('tg_username', models.CharField(max_length=100)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
    ]
