# Generated by Django 5.0.6 on 2024-05-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('numbers', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('cvc', models.CharField(max_length=3)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='session',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
