# Generated by Django 5.0.6 on 2024-05-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_remove_userdata_session_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
