# Generated by Django 5.0.6 on 2024-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_card_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
